### PR TITLE
Tribbles Image

### PR DESCRIPTION
**Pull request by the-code-wookie**

### CODE REVIEW

**Comment by the-code-wookie** [comment]
aarrragghuuhw uughguughhhghghghhhgh wuuh aarrragghuuhw uughguughhhghghghhhgh uughghhhgh wrrhw aarrragghuuhw?

**Comment by taelor** [comment]
It's OK code-wook, I don't expect you to know how to do everything, try linking to raw file, it has to be on github somewhere.

**Comment by taelor** [comment]
This looks much better now, I can even see the picture in your fork. There seems to be a merge conflict, so can you pull the changes from upstream and resolve it?

**Comment by the-code-wookie** [comment]
wuuh aarrragghuuhw aarrragghuuhw  uuh raaaaaahhgh aarrragghuuhw

**Pull request merged**
